### ISSUE TITLE
Define Eclipse Platform versions to be supported 

### ISSUE THREAD

**Issue by ruspl-afed** [platformio/platformio-eclipse-ide#3]
It is important to define Eclipse Platform versions to be supported.
For example the latest released Eclipse 2020-06 uses Java 8 while the upcoming Eclipse 2020-09 requires Java 11.

I plan to start with the latest released 2020-06 but we need to define the list of supported versions anyway,

**Comment by ivankravets** [comment]
@ruspl-afed I think 2020-06 is a good starting point. We can upgrade any time. It impossible to downgrade source code.

**Comment by ruspl-afed** [comment]
> It impossible to downgrade source code

Yes, I would avoid doing it for free :) But we always can create a branch to support older versions of Eclipse if someone wants to pay for it.

**Comment by ivankravets** [comment]
Do we need any features from Java 11 that block our tasks? What I known, JetBrains uses Java 8 for all their products. I think we can move with it as well.

**Comment by ruspl-afed** [comment]
> Do we need any features from Java 11 that block our tasks?

Nope, we are not blocked by anything. And I would stick our functionality to Java 8 for a while.

>  JetBrains uses Java 8 for all their products

God bless them, but I don't care as they are living in another world. What I do care about when I implementing Eclipse-related functionality is Eclipse Platform.
And Eclipse Platform requires Java 11 to be executed. But again, it will not affect us for a while as we are just an additional feature for an existing Eclipse product that we will install on. 

Later - after we will upgrade this repository to produce self-sufficient Eclipse product, not just an Eclipse feature to upgrade others -  we may need to think about Java 11.

**Comment by ivankravets** [comment]
Got you! Thanks for the detailed explanation! 👍

**Comment by ruspl-afed** [comment]
Since we need to have modern browser support our target platform is >= Eclipse SimRel 2020-12
So, I think that this issue can be closed
